function findIntent(code)
{
const intentList = {
    "bal_cd_mrt": "Get CD Balance at Maturity",
    "cd_depamnt": "Get CD Opening Deposit Amount",
    "bal_chkn_min": "Get Checking Account Minimum Balance",
    "bal_svg_min": "Get Savings Account minimum balance",
    "bal": "Get Balance",
    "cc_minpmnt_due": "Get Credit Card Minimum Payment Due Amount",
    "lin_minpmnt_due": "Get Line of Credit Minimum Payment Due Amount",
    "lon_mnth_pmnt": "get loan monthly payment amount",
    "mrtg_mnth_pmnt": "get mortgage monthly payment amount",
    "cc_mnth_pmnt_duedt": "Get Credit Card Monthly Payment Due Date",
    "lin_mnth_pmnt_duedt": "get line of credit monthly payment due date",
    "lon_mnth_pmnt_duedt": "Get Loan Monthly Payment Details",
    "mrtg_pmnt_duedt": "get mortgage payment due date",
    "cc_cycdt": "get credit card cycle date.",
    "acc_cycdt": "get account cycle date",
    "chkn_acc_cycdt": "get account cycle date",
    "svg_acc_cycdt": "get account cycle date",
    "cd_acc_cycdt": "get account cycle date",
    "cc_acc_cycdt": "get account cycle date",
    "lon_acc_cycdt": "get account cycle date",
    "lin_acc_cycdt": "get account cycle date",
    "mrtg_acc_cycdt": "get account cycle date",
    "ira_acc_cycdt": "get account cycle date",
    "mrtg_payoff": "get mortgage payoff amount",
    "get_lon_payoff": "get loan payoff amount",
    "lin_payoff": "get line payoff amount",
    "get_lon_origamnt": "get loan origination amount",
    "mrtg_origamnt": "get mortgage origination amount",
    "get_affrd_buy": "Get Affordability",
    "acc_addr": "Get Address on Account",
    "acc_chkn_addr": "Get Address on Account",
    "acc_svg_addr": "Get Address on Account",
    "acc_cd_addr": "Get Address on Account",
    "acc_cc_addr": "Get Address on Account",
    "acc_lon_addr": "Get Address on Account",
    "acc_lin_addr": "Get Address on Account",
    "mrtg_addr": "Get Address on Account",
    "ira_addr": "Get Address on Account",
    "get_cust_addr": "Get Profile Address",
    "get_acc_email": "Get Email on Account",
    "acc_chkn_email": "Get Email on Account",
    "acc_svg_email": "Get Email on Account",
    "acc_cd_email": "Get Email on Account",
    "acc_cc_email": "Get Email on Account",
    "acc_lon_email": "Get Email on Account",
    "acc_lin_email": "Get Email on Account",
    "mrtg_email": "Get Email on Account",
    "ira_email": "Get Email on Account",
    "get_cust_email": "Get Profile Email",
    "acc_phn": "Get Phone Number on Account",
    "acc_chkn_phn": "Get Phone Number on Account",
    "acc_svg_phn": "Get Phone Number on Account",
    "acc_cd_phn": "Get Phone Number on Account",
    "acc_cc_phn": "Get Phone Number on Account",
    "acc_lon_phn": "Get Phone Number on Account",
    "acc_lin_phn": "Get Phone Number on Account",
    "mrtg_phn": "Get Phone Number on Account",
    "ira_phn": "Get Phone Number on Account",
    "get_cust_phn": "get profile phone number",
    "get_cust_prim_phn": "get profile phone number",
    "get_cust_alt_phn": "get profile phone number",
    "cust_name": "Get Profile Name",
    "acc_name": "Get Name on Account",
    "acc_chkn_name": "Get Name on Account",
    "acc_svg_name": "Get Name on Account",
    "acc_cd_name": "Get Name on Account",
    "acc_cc_name": "Get Name on Account",
    "acc_lon_name": "Get Name on Account",
    "acc_lin_name": "Get Name on Account",
    "mrtg_name": "Get Name on Account",
    "ira_name": "Get Name on Account",
    "bnk_info": "Get Personal Banker Information",
    "bnk_email": "Get Personal Banker Information",
    "bnk_phn": "Get Personal Banker Information",
    "bnk_name": "Get Personal Banker Information",
    "bnk_addr": "Get Personal Banker Information",
    "get_cd_matdt": "get cd maturity date",
    "get_lon_matdt": "get loan maturity date",
    "mrtg_matdt": "get mortgage maturity date",
    "chqbk_avl": "get check book facility availability status",
    "get_dbtcrdexp": "get debit card expiration date",
    "get_cc_exp": "get credit card expiration date",
    "get_dbtcrdnum": "get debit card number",
    "get_acc_num": "get account number",
    "chkn_accnum": "get account number",
    "svg_accnum": "get account number",
    "cd_accnum": "get account number",
    "cc_accnum": "get account number",
    "lon_accnum": "get account number",
    "lin_accnum": "get account number",
    "mrtg_accnum": "get account number",
    "ira_accnum": "get account number",
    "get_cc_crdnum": "get credit card number",
    "get_acc_nick": "get account Nickname",
    "chkn_accnick": "get account Nickname",
    "svg_accnick": "get account Nickname",
    "cd_accnick": "get account Nickname",
    "cc_accnick": "get account Nickname",
    "lon_accnick": "get account Nickname",
    "lin_accnick": "get account Nickname",
    "mrtg_accnick": "get account Nickname",
    "ira_accnick": "get account Nickname",
    "acc_dtls": "get Account Details",
    "acc_chkn_dtls": "get Account Details",
    "acc_svg_dtls": "get Account Details",
    "acc_cd_dtls": "get Account Details",
    "acc_cc_dtls": "get Account Details",
    "acc_lon_dtls": "get Account Details",
    "acc_lin_dtls": "get Account Details",
    "acc_mrtg_dtls": "get Account Details",
    "acc_ira_dtls": "get Account Details",
    "acc_relshp": "get account relationship type",
    "chkn_relshp": "get account relationship type",
    "svg_relshp": "get account relationship type",
    "cd_relshp": "get account relationship type",
    "cc_relshp": "get account relationship type",
    "lon_relshp": "get account relationship type",
    "lin_relshp": "get account relationship type",
    "mrtg_relshp": "get account relationship type",
    "ira_relshp": "get account relationship type",
    "iban": "get iban number",
    "acc_chkn_iban": "get iban number",
    "acc_svg_iban": "get iban number",
    "acc_cd_iban": "get iban number",
    "acc_cc_iban": "get iban number",
    "lon_iban": "get iban number",
    "lin_iban": "get iban number",
    "mrtg_iban": "get iban number",
    "ira_iban": "get iban number",
    "acc_rout": "get routing number",
    "acc_chkn_rout": "get routing number",
    "acc_svg_rout": "get routing number",
    "acc_cd_rout": "get routing number",
    "acc_cc_rout": "get routing number",
    "acc_lon_rout": "get routing number",
    "acc_lin_rout": "get routing number",
    "acc_mrtg_rout": "get routing number",
    "acc_ira_rout": "get routing number",
    "get_lin_lstdrwdt": "get line of credit last draw date",
    "get_lon_origdt": "get loan origination date",
    "mrtg_origdt": "get mortgage origination date",
    "acc_opndt": "get Account Opening date",
    "acc_lon_opndt": "get Account Opening date",
    "acc_svg_opndt": "get Account Opening date",
    "acc_chkn_opndt": "get Account Opening date",
    "ira_opndt": "get Account Opening date",
    "cd_opndt": "get Account Opening date",
    "mrtg_opndt": "get Account Opening date",
    "cc_opndt": "get Account Opening date",
    "get_mrtg_propaddr": "get mortgage property address",
    "crd_actvdt": "get card activation date",
    "cc_actvdt": "get card activation date",
    "dbt_actvdt": "get card activation date",
    "acc_clsrsts": "Get Account closure Status",
    "accsts": "get account status",
    "chkn_accsts": "get account status",
    "svg_accsts": "get account status",
    "cd_accsts": "get account status",
    "cc_accsts": "get account status",
    "lon_accsts": "get account status",
    "lin_accsts": "get account status",
    "mrtg_accsts": "get account status",
    "ira_accsts": "get account status",
    "acc_stmt": "get account statements",
    "pmnt_hist": "get payment history",
    "acc_txn": "get account transactions",
    "acc_txn_pstdt": "get account transactions",
    "acc_txn_amnt": "get account transactions",
    "acc_txn_ctyst": "get account transactions",
    "pmnt_intamnt": "get payment interest amount",
    "cc_pmnt_intamnt": "get payment interest amount",
    "mrtg_pmnt_intamnt": "get payment interest amount",
    "lon_pmnt_intamnt": "get payment interest amount",
    "lin_pmnt_intamnt": "get payment interest amount",
    "txn_hist": "get payment interest amount",
    "atm_brn_hrs": "get atm or branch hours",
    "atm_brn_loc": "get atm or branch location",
    "atm_brn_serv_prov": "get atm or branch services provided",
    "tech_supp": "get technical support",
    "pay_blr": "Pay a Biller",
    "recr_bll_pay": "Set up Recurring Bill Pay",
    "add_ebll": "Add An Ebill",
    "add_aut_ebll_pmnt": "Add Auto Ebill Payments",
    "lin_draw": "Make a Credit Line Draw",
    "one_time_int": "Make Internal One Time Transfer",
    "one_time_lon_int": "Make Internal One Time Transfer",
    "one_time_lin_int": "Make Internal One Time Transfer",
    "one_time_mrtg_mly_pmnt": "Make Internal One Time Transfer",
    "one_time_cc_int": "Make Internal One Time Transfer",
    "one_time_dep_int": "Make Internal One Time Transfer",
    "schtrns": "Schedule a Transfer",
    "sch_lon_pmnt": "Schedule a Transfer",
    "sch_lin_pmnt": "Schedule a Transfer",
    "sch_mrtg_pmnt": "Schedule a Transfer",
    "sch_cc_pmnt": "Schedule a Transfer",
    "sch_dep_acct": "Schedule a Transfer",
    "recr_int": "Set up Recurring Internal Bank Transfer",
    "recr_lon_pmnt": "Set up Recurring Internal Bank Transfer",
    "recr_lin_pmnt": "Set up Recurring Internal Bank Transfer",
    "recr_mrtg_pmnt": "Set up Recurring Internal Bank Transfer",
    "recr_cc_pmnt": "Set up Recurring Internal Bank Transfer",
    "recr_trnsfr_dep_acct": "Set up Recurring Internal Bank Transfer",
    "mkp2p": "Make a P2P Payment",
    "req_p2p": "Request a P2p Payment",
    "sch_p2p": "Schedule a P2P Payment",
    "recr_p2p": "Set up Recurring a P2P Payment",
    "splt_p2p": "Split a P2p Payment",
    "cc_mkcshadv": "make a credit card cash advance",
    "sch_bll_pmnt": "Schedule a bill payment",
    "cncl_bnk_recrtrns": "Cancel Recurring Internal Bank Transfer",
    "cncl_recr_lon_pmnt": "Cancel Recurring Internal Bank Transfer",
    "cncl_recr_lin_pmnt": "Cancel Recurring Internal Bank Transfer",
    "cncl_mrtg_pmnt": "Cancel Recurring Internal Bank Transfer",
    "cncl_recr_cc_pmnt": "Cancel Recurring Internal Bank Transfer",
    "cncl_recr_trnsfr_dep_acct": "Cancel Recurring Internal Bank Transfer",
    "cncl_shl_bnk_int": "Cancel Scheduled  Internal Bank Transfer",
    "cncl_shl_lon_pmnt": "Cancel Scheduled  Internal Bank Transfer",
    "cncl_shl_lin_pmnt": "Cancel Scheduled  Internal Bank Transfer",
    "cncl_shl_mrtg_pmnt": "Cancel Scheduled  Internal Bank Transfer",
    "cncl_shl_cc_pmnt": "Cancel Scheduled  Internal Bank Transfer",
    "cncl_shl_trnsfr_dep_acct": "Cancel Scheduled  Internal Bank Transfer",
    "upd_recr_int_bnk": "Update Recurring Transfers to Internal Bank",
    "upd_recr_lon_pmnt": "Update Recurring Transfers to Internal Bank",
    "upd_recr_lin_pmnt": "Update Recurring Transfers to Internal Bank",
    "upd_recr_mrtg_pmnt": "Update Recurring Transfers to Internal Bank",
    "upd_recr_cc_pmnt": "Update Recurring Transfers to Internal Bank",
    "upd_recr_trnsfr_dep_acct": "Update Recurring Transfers to Internal Bank",
    "upd_sch_int_bnk": "Update Scheduled Transfers to Internal Bank",
    "upd_sch_lon_pmnt": "Update Scheduled Transfers to Internal Bank",
    "upd_sch_lin_pmnt": "Update Scheduled Transfers to Internal Bank",
    "upd_sch_mrtg_pmnt": "Update Scheduled Transfers to Internal Bank",
    "upd_sch_cc_pmnt": "Update Scheduled Transfers to Internal Bank",
    "upd_sch_trnsfr_dep_acct": "Update Scheduled Transfers to Internal Bank",
    "acc_edit_addr": "Update Address on the Account",
    "chkn_acc_edit_addr": "Update Address on the Account",
    "svg_acc_edit_addr": "Update Address on the Account",
    "cd_acc_edit_addr": "Update Address on the Account",
    "cc_acc_edit_addr": "Update Address on the Account",
    "lon_acc_edit_addr": "Update Address on the Account",
    "lin_acc_edit_addr": "Update Address on the Account",
    "mrtg_acc_edit_addr": "Update Address on the Account",
    "ira_acc_edit_addr": "Update Address on the Account",
    "editcust_addr": "Update Profile Address",
    "acc_edit_email": "Update Email on the Account",
    "chkn_acc_edit_email": "Update Email on the Account",
    "svg_acc_edit_email": "Update Email on the Account",
    "cd_acc_edit_email": "Update Email on the Account",
    "cc_acc_edit_email": "Update Email on the Account",
    "lon_acc_edit_email": "Update Email on the Account",
    "lin_acc_edit_email": "Update Email on the Account",
    "mrtg_acc_edit_email": "Update Email on the Account",
    "ira_acc_edit_email": "Update Email on the Account",
    "editcust_email": "Update Profile Email",
    "acc_edit_phn": "Update Phone Number on the Account",
    "chkn_acc_edit_phn": "Update Phone Number on the Account",
    "svg_acc_edit_phn": "Update Phone Number on the Account",
    "cd_acc_edit_phn": "Update Phone Number on the Account",
    "cc_acc_edit_phn": "Update Phone Number on the Account",
    "lon_acc_edit_phn": "Update Phone Number on the Account",
    "lin_acc_edit_phn": "Update Phone Number on the Account",
    "mrtg_acc_edit_phn": "Update Phone Number on the Account",
    "ira_acc_edit_phn": "Update Phone Number on the Account",
    "editcust_phn": "Update Profile Phone Number",
    "editcust_prim_phn": "Update Profile Phone Number",
    "editcust_alt_phn": "Update Profile Phone Number",
    "edit_accname": "Update Name on the Account",
    "edit_chkn_accname": "Update Name on the Account",
    "edit_svg_accname": "Update Name on the Account",
    "edit_cd_accname": "Update Name on the Account",
    "edit_cc_accname": "Update Name on the Account",
    "edit_lon_accname": "Update Name on the Account",
    "edit_lin_accname": "Update Name on the Account",
    "edit_mrtg_accname": "Update Name on the Account",
    "edit_ira_accname": "Update Name on the Account",
    "editcust_name": "Update Profile Name",
    "edit_accnick": "Update Account Nickname",
    "edit_chkn_accnick": "Update Account Nickname",
    "edit_svg_accnick": "Update Account Nickname",
    "edit_cd_accnick": "Update Account Nickname",
    "edit_cc_accnick": "Update Account Nickname",
    "edit_lon_accnick": "Update Account Nickname",
    "edit_lin_accnick": "Update Account Nickname",
    "edit_mrtg_accnick": "Update Account Nickname",
    "edit_ira_accnick": "Update Account Nickname",
    "reset_onlnbnk_pscd": "Reset Online or Mobile Banking passcode",
    "crd_blk_remcnty": "Remove card block at country",
    "cc_blk_remcnty": "Remove card block at country",
    "dbt_blk_remcnty": "Remove card block at country",
    "crd_blk_remmerc": "Remove card block at merchant",
    "cc_blk_remmerc": "Remove card block at merchant",
    "dbt_blk_remmerc": "Remove card block at merchant",
    "tmp_blk_purall": "Remove temporary block for all purchases",
    "cc_tmp_blk_purall": "Remove temporary block for all purchases",
    "dbt_tmp_blk_purall": "Remove temporary block for all purchases",
    "crd_unlck": "unlock card",
    "cc_unlck": "unlock card",
    "dbt_unlck": "unlock card",
    "crd_blk_lst": "Block lost card",
    "cc_blk_lst": "Block lost card",
    "dbt_blk_lst": "Block lost card",
    "crd_blk_stln": "Block stolen card",
    "cc_blk_stln": "Block stolen card",
    "dbt_blk_stln": "Block stolen card",
    "pur_tmp_blkall": "Place temporary block for all purchases",
    "pur_tmp_cc_blkall": "Place temporary block for all purchases",
    "pur_tmp_dbt_blkall": "Place temporary block for all purchases",
    "tmp_blkmerc": "Place temporary block for merchant",
    "cc_tmp_blkmerc": "Place temporary block for merchant",
    "dbt_tmp_blkmerc": "Place temporary block for merchant",
    "tmp_blkcnty": "Place temporary block on country",
    "cc_tmp_blkcnty": "Place temporary block on country",
    "dbt_tmp_blkcnty": "Place temporary block on country",
    "crd_stkatm": "report card Stuck in ATM",
    "cc_crd_stkatm": "report card Stuck in ATM",
    "dbt_crd_stkatm": "report card Stuck in ATM",
    "crd_dmg": "report card damage",
    "cc_dmg": "report card damage",
    "dbt_dmg": "report card damage",
    "crd_rplodr": "Order replacement card",
    "cc_rplodr": "Order replacement card",
    "dbt_rplodr": "Order replacement card",
    "blrname": "Get Name of the Biller",
    "regdblr": "Get Registered Billers",
    "payee": "Get Payees",
    "trnf_recr": "Get Recurring Transfers",
    "trnf_schd": "Get Scheduled Transfers",
    "bll_recr_pmnt": "Get Recurring Bill Payments",
    "bll_schd_pmnt": "Get Scheduled Bill Payments",
    "p2p_schd_pmnt_dtls": "Get Scheduled P2P payment details",
    "p2p_recr_pmnt_dtls": "Get Recurring P2P payment details",
    "pinrset": "reset pin",
    "cc_pinrset": "reset pin",
    "dbt_pinrset": "reset pin",
    "set_tvlntfn": "Set Travel Notification",
    "dbtcrd_set_tvlntfn": "Set Travel Notification",
    "cc_set_tvlntfn": "Set Travel Notification",
    "get_cd_intrt": "get cd interest rate",
    "acc_chkn_intrt": "Get Checking Account Interest Rate",
    "cc_cshintrt": "Get Credit Card Cash Interest Rate",
    "lin_intrt": "Get Line of Credit Interest Rate",
    "lon_intrt": "get interest rate on loan",
    "mrtg_intrt": "get mortgage interest rate",
    "acc_svg_intrt": "Get Savings Account Interest Rate",
    "addblr": "Add a Biller",
    "addpapblr": "Add a Biller",
    "addeblr": "Add a Biller",
    "addindblr": "Add a Biller",
    "addpay": "Add a Payee",
    "editblr": "Update a Biller",
    "editpay": "Update a Payee",
    "delblr": "Delete a Biller",
    "delpay": "Delete a Payee",
    "edit_recrp2p_pmnt": "Update a Recurring P2P Payment",
    "edit_schp2p_pmnt": "Update a Scheduled P2P Payment",
    "stp_autpay": "Stop Auto Pay",
    "delebll": "Delete An Ebill",
    "delebll_autpay": "Delete An Ebill Auto Payment",
    "del_recrp2p_pmnt": "Delete a Recurring P2P Payment",
    "del_schp2p_pmnt": "Delete a Scheduled P2P Payment",
    "edit_recr_bll_pmnt": "Update recurring bill payment",
    "edit_sch_bll_pmnt": "Update scheduled bill payment",
    "cncl_recr_bll_pmnt": "Cancel recurring bill payment",
    "cncl_sch_bll_pmnt": "Cancel scheduled bill payment",
    "cc_cshadvlmt": "get credit card cash advance limit",
    "chkng_acc_cshdeplmt": "get checking account cash deposit limit",
    "chkng_accfnd_trnsfrlmt": "get checking account fund transfer limits",
    "chkng_acctxn_lmt": "Get Checking account transaction Limits",
    "cc_credlmt": "get credit card Credit limit",
    "lin_credlmt": "get line of credit credit limit",
    "svg_acccsh_deplmt": "get savings account cash deposit limit",
    "svg_accfnd_trnsfrlmt": "get savings account fund transfer limits",
    "svg_txnlmt": "get savings account transaction limits",
    "crdtxn_lmt": "get card transaction limit",
    "cc_txn_lmt": "get card transaction limit",
    "dbt_txn_lmt": "get card transaction limit",
    "cc_cshadvlmt_supcrd": "get credit card cash advance limit for supplementary card",
    "txnlmt_supcrd": "get transaction limit for supplementary card",
    "atm_lmt": "get atm limits",
    "dbtdly_atm_wdlamt_lmt": "get atm limits",
    "dbtmly_atm_wdlamt_lmt": "get atm limits",
    "ccdly_atm_wdlamt_lmt": "get atm limits",
    "ccmly_atm_wdlamt_lmt": "get atm limits",
    "txnlmt": "get purchase transaction limits",
    "dbt_dly_txnlmt": "get purchase transaction limits",
    "dbt_mly_txnlmt": "get purchase transaction limits",
    "dbt_per_txnlmt": "get purchase transaction limits",
    "dbt_num_day_txnlmt": "get purchase transaction limits",
    "cc_dly_txnlmt": "get purchase transaction limits",
    "cc_mly_txnlmt": "get purchase transaction limits",
    "cc_per_txnlmt": "get purchase transaction limits",
    "cc_num_day_txnlmt": "get purchase transaction limits",
    "trnsfr_lmt": "get transfer limits",
    "cc_avlcred": "get credit card available credit",
    "cc_avlcsh_amt": "get credit card available credit",
    "lin_avlcred": "get line of credit available credit",
    "deccrd_credlmt": "decrease card credit limit",
    "decsupcrd_credlmt": "decrease supplementary card credit limit",
    "inccrd_credlmt": "increase card credit limit",
    "supcrd_credlmt": "increase supplementary card credit limit",
    "cshdep_lmtinc": "request a cash deposit limit increase",
    "editatm_lmt": "update atm limits",
    "editatm_dly_dbt_wdlamt_lmt": "update atm limits",
    "editatm_mly_dbt_wdlamt_lmt": "update atm limits",
    "editatm_dly_cc_wdlamt_lmt": "update atm limits",
    "editatm_mly_cc_wdlamt_lmt": "update atm limits",
    "edittxn_lmt": "update transactions limits",
    "edit_dbt_dly_pur_amt_lmt": "update transactions limits",
    "edit_dbt_mly_pur_amt_lmt": "update transactions limits",
    "edit_dbt_per_pur_amt_lmt": "update transactions limits",
    "edit_dbt_num_pur_day_lmt": "update transactions limits",
    "edit_cc_dly_pur_amt_lmt": "update transactions limits",
    "edit_cc_mly_pur_amt_lmt": "update transactions limits",
    "edit_cc_per_pur_amt_lmt": "update transactions limits",
    "edit_cc_num_pur_day_lmt": "update transactions limits",
    "edit_trnsfrlmt": "update transfer limits",
    "aply_lon": "apply for a loan",
    "aply_acc_cc": "apply for credit card account",
    "aply_acc_mrtg": "apply for mortgage account",
    "opn_cd": "open a CD",
    "opn_acc_chkn": "open checking account",
    "opn_acc_svg": "open savings account",
    "aply_lon_tpup": "Apply for Loan Topup",
    "add_crd_supl": "Add a supplementary card",
    "acc_clsrreq": "request account closure",
    "acc_chkn_clsrreq": "request account closure",
    "acc_svg_clsrreq": "request account closure",
    "acc_cd_clsrreq": "request account closure",
    "acc_lin_clsrreq": "request account closure",
    "acc_lon_clsrreq": "request account closure",
    "acc_mrtg_clsrreq": "request account closure",
    "papstmt": "Get Paper Statement",
    "trn_offon_estmt": "Turn off Or on Estatements",
    "trn_on_estmt": "Turn off Or on Estatements",
    "trn_off_estmt": "Turn off Or on Estatements",
    "crd_acvt": "activate card",
    "cc_actvt": "activate card",
    "dbt_actvt": "activate card",
    "dep_mak": "make a deposit",
    "dep_chk": "make a deposit",
    "txn_dis": "Dispute a card transaction",
    "unlk_onlmbnkg": "unlock online or mobile banking.",
    "pstpn_lon_pmnt": "postpone loan payment",
    "chkbk_new": "get a new checkbook",
    "rwdpnt_bal": "get rewards points balance",
    "snd_secmsg": "send secure message",
    "fdbk_prov": "provide feedback",
    "crdtscr": "get credit score",
    "applsts": "get account application status",
    "chkn_applsts": "get account application status",
    "svg_applsts": "get account application status",
    "cd_applsts": "get account application status",
    "cc_applsts": "get account application status",
    "lon_applsts": "get account application status",
    "lin_applsts": "get account application status",
    "mrtg_applsts": "get account application status",
    "ira_applsts": "get account application status",
    "set_appr_crdlmtalt": "set approaching credit limit alert",
    "set_cc_bllpdalt": "set Credit Card Bill Paid alert",
    "set_onln_puralt": "set online purchase alert",
    "set_pmnt_duealt": "set payment due alert",
    "set_dlybalalt": "set daily balance alert",
    "set_lowbalalt": "set low balance alert.",
    "set_chkn_lowbalalt": "",
    "set_svg_lowbalalt": "",
    "set_acc_ovd_alrt": "Set account overdrawn alert",
    "chkbk_delsts": "get checkbook delivery status",
    "new_crd_dlvysts": "get delivery status of new card",
    "new_cc_dlvysts": "get delivery status of new card",
    "new_dbt_dlvysts": "get delivery status of new card",
    "bll_pmntsts": "get bill payment status",
    "req_feewvr": "request a fee waiver",
    "rev_fee_int": "request a fee waiver",
    "req_fewvr": "request a fee waiver",
    "req_crd_balrfd": "request credit balance refund.",
    "login": "Log in",
    "phn_lgn": "Log in",
    "phn_onln_mbl_bnk": "Log in",
    "acc_chkn_fee": "get checking account fees",
    "acc_cc_fee": "get credit card account fees",
    "acc_svg_fee": "get savings account fees",
    "txn_decl_rpt": "report decline transaction",
    "IA_bal": "Get Balance",
    "IA_txn_dis": "Dispute a card transaction",
    "addrem_joint_ah": "Add or remove joint Account holders",
    "add_joint_ah": "Add joint account holders",
    "rem_joint_ah": "Remove joint account holders",
    "del_auth_usr": "delete authorized user",
    "wire_trnsfr_lmt": "get wire transfer limit",
    "new_pymt_dd": "Request new Payment Due Date",
    "third_party_trans": "transfer to third-party within the same Bank",
    "unlock_onmob": "Unlock online or mobile banking",
    "od_fee": "Get Overdraft account Fee",
    "set_atpay_lc": "Set auto pay for Loans and Cards",
    "sch_trnsfr_extbank": "schedule transfer to external bank",
    "ext_acc_diff": "Add an External Account from different bank",
    "cncl_recc_ext": "Cancel Recurring transfers to external bank",
    "cncl_sch_ext": "cancel scheduled transfer to external bank",
    "cncl_dom_wt": "Cancel domestic Wire transfer",
    "cncl_intl_wt": "Cancel international Wire transfer",
    "rep_incc_bal": "report incorrect balance",
    "dom_wt": "initiate domestic wire transfer",
    "dom_ele_wt": "initiate ach/ domestic electronic transfers",
    "intl_wt": "initiate international wire transfer",
    "wt_fee": "get wire transfer fee",
    "req_for_tax_doc": "Request Tax Document",
    "req_hld_rel": "request hold release",
    "check_hld_rel": "request check hold release",
    "ele_hld_rel": "request electronic payment hold release",
    "dip_nc_txn": "Dispute non Card transaction",
    "wt_deltime": "get wire transfer delivery time",
    "rep_fraud": "report fraud"
}

return intentList[code];

}

module.exports=findIntent;